name: Build LetRecovery Windows

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-all:
    runs-on: windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - uses: fcurrk/toolchain@master
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: build Desktop
        working-directory: desktop
        run: cargo build --release --all-features --target=x86_64-pc-windows-msvc

      - name: build pe
        working-directory: pe
        run: cargo build --release --all-features --target=x86_64-pc-windows-msvc

      - name: Commit and push Cargo.lock updates
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add desktop/Cargo.toml desktop/Cargo.lock pe/Cargo.toml pe/Cargo.lock
          git diff --quiet && git diff --staged --quiet || git commit -m "Update Cargo.lock for both projects"
          git push

      - name: Upload Desktop artifacts
        uses: actions/upload-artifact@v4
        with:
          name: LetRecovery-Desktop
          path: desktop/target/x86_64-pc-windows-msvc/release/LetRecovery.exe
          retention-days: 30

      - name: Upload PE artifacts
        uses: actions/upload-artifact@v4
        with:
          name: LetRecovery-PE
          path: pe/target/x86_64-pc-windows-msvc/release/LetRecoveryPE.exe
          retention-days: 30