name: Build LetRecovery Windows

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-all:
    runs-on: windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - uses: fcurrk/toolchain@master
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: build Desktop
        env:
          SERVER_BASE_URL: ${{ secrets.SERVER_BASE_URL }}
        working-directory: desktop
        run: |
          cargo build --release
          if (Test-Path "..\Cargo.lock") {
            Write-Host "Found Cargo.lock, copying to desktop..."
            Copy-Item "..\Cargo.lock" "Cargo.lock"
          } else {
            Write-Host "Cargo.lock not found in root directory"
          }
        shell: pwsh

      - name: build pe
        env:
          SERVER_BASE_URL: ${{ secrets.SERVER_BASE_URL }}
        working-directory: pe
        run: |
          cargo build --release
          if (Test-Path "..\Cargo.lock") {
            Write-Host "Found Cargo.lock, copying to pe..."
            Copy-Item "..\Cargo.lock" "Cargo.lock"
          } else {
            Write-Host "Cargo.lock not found in root directory"
          }
        shell: pwsh

      - name: Commit Cargo.lock
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          $hasDesktop = Test-Path "desktop/Cargo.lock"
          $hasPe = Test-Path "pe/Cargo.lock"

          if ($hasDesktop) {
              Write-Host "desktop/Cargo.lock found"
              git add desktop/Cargo.lock
            } else {
              Write-Host "desktop/Cargo.lock not found"
          }
          if ($hasPe) {
            Write-Host "pe/Cargo.lock found"
            git add pe/Cargo.lock
          } else {
            Write-Host "pe/Cargo.lock not found"
          }

          if ($hasDesktop -or $hasPe) {
            Write-Host "Committing Cargo.lock updates..."
            git diff --quiet && git diff --staged --quiet
            if ($LASTEXITCODE -ne 0) {
              git commit -m "Update Cargo.lock"
              git push
            } else {
              Write-Host "No changes to Cargo.lock"
            }
          } else {
            Write-Host "No Cargo.lock files found in desktop or pe, skipping commit"
          }
        shell: pwsh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: LetRecovery
          path: target/release/*.exe
          retention-days: 30